import Head from 'next/head'
import Image from 'next/image'

import { Inter } from '@next/font/google'
import { NextPage } from 'next'


import Header from '@/components/Header'
import Card from '@/components/Card'


const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Golf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-screen rsg-background'>
        <Header />
        <div className='flex flex-row flex-wrap justify-center pt-32'>
          <Card image="/tourn.png" alt="golf_images" title="Tournaments" description='The annual Golf Classic tournament card features a beautiful 18-hole course surrounded by scenic views. Participants will enjoy a day of friendly competition while playing on well-manicured greens' link="/" />
          <Card image="/round.png" alt="round" title="Courses" description='Look back on your recent rounds, alongside each shot' link="/courses" />
          <Card image="/golf.png" alt="golf" title="Leaderboards" description='See who is playing well in current tournaments' link="/" />
        </div>
      </div>
    </div>
  )
}

export default Home;